### ISSUE TITLE
ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []

### ISSUE THREAD

**Issue by dkguru** [Azure/WALinuxAgent#1393]
Hi,

I currently got this spamming our log every 5 seconds. Not sure when it started:

2018/11/11 23:52:07.462291 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []

Can't find anything in other logs indicating WHY.

Any ideas anyone?

**Comment by vrdmr** [comment]
Hi @dkguru - Can you please let us know the version of the guest agent (output of the `waagent -version` command) and the distro information.

**Comment by adamprice2** [comment]
Same problem, same waagent version as uhoxx

**Comment by uhoxx** [comment]
I started systemd-networkd.service and now its not spamming console.

**Comment by OwainWin** [comment]
I have a similar issue since upgrading to 2.2.33 where messages is spammed every 1 minute with the following:
python: 2018/11/26 16:12:34.716525 WARNING ExtHandler Monitor: failed to collect cgroups performance metrics: 'NoneType' object has no attribute '__getitem__'

WALinuxAgent-2.2.18 running on centos 7.5.1804
Python: 2.7.5
Goal state agent: 2.2.33

Remove the agent, re-installing and in /etc/waagent.conf enabling and setting AutoUpdate.Enabled=n stops the agent from being upgraded again - this is only a work around.

**Comment by boostnest** [comment]
Have the same issue on my Azure VM Ubantu 18 however mine is erroring ever 5 seconds in the console making it hard to try and fix. Haven't had any luck as yet.....

**Comment by OwainWin** [comment]
waagent 2.2.34 looks to have fixed this for me
I was getting:

python: 2018/11/26 16:12:34.716525 WARNING ExtHandler Monitor: failed to collect cgroups performance metrics: 'NoneType' object has no attribute 'getitem'

But there have been no more occurrences of this since the waagent was updated to 2.2.34.

**Comment by boostnest** [comment]
Have upgraded to 2.2.34 and still having the issue on Ubuntu 18 running on Azure.

**Comment by paos** [comment]
Same issue on ubuntu 18.04: this message is in the console every 5 sec:
2018/12/17 11:10:26.381986 ERROR ExtHandler Command: [pidof systemd-networkd], return code: [1], result: []

WALinuxAgent-2.2.20 running on ubuntu 18.04
Python: 3.6.7
Goal state agent: 2.2.34

Restarting systemd-networkd.service has not helped. I don't know how to fix this.

**Comment by andschwa** [comment]
Same issue here. Installed a 16.04 VM, upgraded to 18.04, and now this is spamming the console.

**Comment by rcarmo** [comment]
I have exactly the same error on 18.04. This is somewhat annoying given that I am tracking ERROR entries in syslog and this is spamming all my debugging stuff.

**Comment by projectje** [comment]
Cool. Cant login anymore to my system. "Login" ... when trying to type something the message spams and login incorrect. Impossible to get through this. Is there any way to suppress this to at least login ?

**Comment by boostnest** [comment]
> Cool. Cant login anymore to my system. "Login" ... when trying to type something the message spams and login incorrect. Impossible to get through this. Is there any way to suppress this to at least login ?

Having this problem also, our Moodle server now cannot be accessed major issue. We might need to move platforms with this continuing to be a problem.

**Comment by dkguru** [comment]
Just wanted to return here and say yes, it works to restart the service with:

`service systemd-networkd restart`

It's still a bug though, and will reoccur when rebooting the server (at least for me)

We can close this thread, however, if it's already in the bug repo.

**Comment by rcarmo** [comment]
I've been finding this across pretty much all the Linux VMs I touch, and am wondering if it's actively being worked on or just queued up...

**Comment by boostnest** [comment]
We have had to move to a new solution as this seemed to create a number of other issues within the VM and made it impossible to troubleshoot.

**Comment by vrdmr** [comment]
Hi, We are currently working on fixing this issue (for both reducing the verbosity of the systemd-networkd (#1577) logs as well as reducing the console logging - #1575 fixing #1465).

For resolving the serial console flooding issue, you can change the config `Logs.Console=n` in `/etc/waagent.conf` (or add, if it is not present) and restart the agent.

Restart waagent service, for most of linux distributions:
```bash
    sudo service waagent restart
```

For Ubuntu, use:
```bash
    sudo service walinuxagent restart
```

For CoreOS, use:
```bash
    sudo systemctl restart waagent
```

**Comment by vrdmr** [comment]
Merged #1577 to reduce the verbosity of the logs and will reduce the spamming of the console.
